### ISSUE TITLE
Getting AttributeError: 'function' object has no attribute 'mkstemp' while running temp.tempfile()

### ISSUE THREAD

**Issue by joylazari** [looking-for-a-job/temp.py#2]
Coming from: https://stackoverflow.com/questions/62778792/python-tempfile-mkstemp-attributeerror-function-object-has-no-attribute-m/62780176

`temp.tempfile()` is triggering the error in the title.

`tempfile.mkstemp()` works like a charm, but:

```python
>>> import temp
>>> temp.tempfile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/temp/__init__.py", line 15, in tempfile
    f, path = tempfile.mkstemp()
AttributeError: 'function' object has no attribute 'mkstemp'
```

I'm kinda sure there's some problem with my local configuration.
I'm on macOS, using python3 (3.7), no virtual envs.

The command `pip list --outdated` tells me that exactly those two libs are actually outdated, but apparently there is no way pip will download the updated versions. (note: my pip is correctly referring to the python3 binary, not macOS outdated python 2.7)

```
osascript 0.0.0   2020.7.2 sdist
temp      0.0.0   2020.7.1 sdist
```

Any ideas?

**Comment by andrewpetrochenkov** [comment]
fixed. my mistakes and experiments, sorry. busy with another
